### ISSUE TITLE
"no such file to load -- spec/rake/spectask" on rake

### ISSUE THREAD

**Issue by zuf** [rugui/rugui#12] opened 2009-08-12 06:28 UTC
Get error whet try see what rake tasks are available.

$ rake --trace -T
(in /home/egor/foo/testrgtk)
rake aborted!
no such file to load -- spec/rake/spectask
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/gems/1.8/gems/rugui-1.3.2/lib/rugui/tasks/spec_application.rake:2
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:145:in`load_without_new_constant_marking'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:145:in `load'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:145:in `load'
/usr/lib/ruby/gems/1.8/gems/rugui-1.3.2/lib/rugui/tasks/rugui.rb:4
/usr/lib/ruby/gems/1.8/gems/rugui-1.3.2/lib/rugui/tasks/rugui.rb:4:in`each'
/usr/lib/ruby/gems/1.8/gems/rugui-1.3.2/lib/rugui/tasks/rugui.rb:4
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:156:in `require'
/home/egor/foo/testrgtk/Rakefile:7
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2383:in`load'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2383:in `raw_load_rakefile'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2017:in`load_rakefile'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2016:in`load_rakefile'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2000:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in`load'
/usr/bin/rake:19

**Comment by rugui** [comment] 2009-08-12 19:29
This error probably happens when you don't have RSpec gem installed. The problem is that RuGUI loads RSpec and Test::Unit tasks for every application created. I'm going to think about a better solution, but for now I will change the file defining RSpec tasks to stop loading tasks if it could not require spec. Something like:

<pre>
begin
  require 'spec'

  # RSpec tasks code here
rescue LoadError
  # RSpec is not installed, no RSpec related task will be used.
end
</pre>


With this, users which don't have RSpec installed will not see RSpec related tasks, once they installed it, those tasks will be available.

**Comment by zuf** [comment] 2009-08-12 19:43
Thank you for explanations. May be it is a good idea to write about this dependency in the readme on main page or add it to gemspec as dependency?

**Comment by rugui** [comment] 2009-08-12 21:07
I've just applied these changes in version 1.3.3. Just update your RuGUI gem:

<pre>
  sudo gem update rugui
</pre>


I'm closing this issue now, if run into errors please let us know.

**Closed as completed by rugui** 2009-08-12 21:07 UTC
Labels: 1.4.0, bug
